#pragma once

/** Arduino: enum'lar #include'lardan once Deskbuddy.ino basinda kalir. */

enum HomeWidgetType {
  HOME_WIDGET_HUMIDITY = 0,
  HOME_WIDGET_TIMER,
  HOME_WIDGET_RAIN,
  HOME_WIDGET_OUTDOOR,
  HOME_WIDGET_KP,
  HOME_WIDGET_UV,
  HOME_WIDGET_WIND,
  HOME_WIDGET_SUN,
  HOME_WIDGET_FINANCE,
  HOME_WIDGET_BUDDY,
  HOME_WIDGET_NOTES,
  HOME_WIDGET_CALENDAR,
  HOME_WIDGET_SPOTIFY,
  HOME_WIDGET_GITHUB
};

constexpr int HOME_SLOT_COUNT = 6;

/** Open-Meteo WMO weather_code */
enum WxKind {
  WX_UNK,
  WX_CLEAR_DAY,
  WX_CLEAR_NIGHT,
  WX_PARTLY,
  WX_CLOUD,
  WX_FOG,
  WX_DRIZZLE,
  WX_RAIN,
  WX_SNOW,
  WX_SHOWER,
  WX_THUNDER
};

enum PageLayout {
  LAYOUT_GRID = 0,
  LAYOUT_FULL_WEATHER = 1,
  LAYOUT_FULL_NOTES = 2,
  LAYOUT_GRID_6 = 3
};

enum Page { PAGE_TAB_0 = 0, PAGE_TAB_1 = 1, PAGE_TAB_2 = 2, PAGE_STATUS = 3 };
